### ISSUE TITLE
Couldn't remove AD

### ISSUE THREAD

**Issue by maRci002** [tomer8007/spotify-web-ads-remover#19]
Toast says `Removed ad` however still got it. This happens after like 50 min but sometimes 20 min.

Till 15:50:42.687 everything was fine, however if ad started and I click to play a new song the ad restarts and get errors on the console, hope the logs helps you.

Log:
```
14:58:47.133 ads_removal.js:26 SpotiAds: Refreshing access token.
14:58:48.485 open.spotifycdn.com/cdn/build/web-player/2789.undefined.css:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
15:27:27.238 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:2GmM6LQfzEyjXXf6VCeXda
15:27:27.239 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:6WWDlsBTEJlZErCcOkfqkt
15:27:27.314 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:2MEbih1xvzJyw1eghLPGTg
15:27:27.315 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:2itNHK7lGiRrcW6P97gGsf
15:27:28.491 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:2MEbih1xvzJyw1eghLPGTg
15:27:57.428 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:2MEbih1xvzJyw1eghLPGTg
15:34:00.020 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:2MEbih1xvzJyw1eghLPGTg
15:34:00.020 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:ad:2MEbih1xvzJyw1eghLPGTg
15:34:00.020 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:63T7DJ1AFDD6Bn8VzG6JE8
15:34:00.049 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:2MEbih1xvzJyw1eghLPGTg
15:34:00.119 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:2MEbih1xvzJyw1eghLPGTg
15:34:00.119 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:ad:2MEbih1xvzJyw1eghLPGTg
15:34:00.119 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:63T7DJ1AFDD6Bn8VzG6JE8
15:34:00.123 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:2MEbih1xvzJyw1eghLPGTg
15:34:00.124 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:ad:2MEbih1xvzJyw1eghLPGTg
15:34:00.124 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:63T7DJ1AFDD6Bn8VzG6JE8
15:34:01.412 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:63T7DJ1AFDD6Bn8VzG6JE8
15:34:30.395 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:63T7DJ1AFDD6Bn8VzG6JE8
15:37:22.486 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:63T7DJ1AFDD6Bn8VzG6JE8
15:45:19.645 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:3hA0NbfUC0aj0pxHHfAILK
15:45:19.651 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:3IN3WiT1AQobNV93cFMz8A
15:45:19.782 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:45:19.826 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:3SaNomu5QJPDCze6jZDDYk
15:45:20.952 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:45:49.920 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:49:38.749 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:49:38.749 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:49:38.750 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:1qatQQKIf1ngj1i8LKtwzq
15:49:38.751 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:49:38.751 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:49:38.751 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:1qatQQKIf1ngj1i8LKtwzq
15:49:38.766 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:49:38.859 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:49:38.859 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:49:38.859 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:1qatQQKIf1ngj1i8LKtwzq
15:49:38.935 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:49:38.935 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:49:38.935 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:1qatQQKIf1ngj1i8LKtwzq
15:49:39.917 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:1qatQQKIf1ngj1i8LKtwzq
15:50:09.631 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:1qatQQKIf1ngj1i8LKtwzq
15:50:16.329 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:50:16.833 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:1qatQQKIf1ngj1i8LKtwzq
15:50:16.842 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:50:16.842 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:50:16.842 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:0SiywuOBRcynK0uKGWdCnn
15:50:17.973 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:0SiywuOBRcynK0uKGWdCnn
15:50:30.444 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:50:30.919 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:0SiywuOBRcynK0uKGWdCnn
15:50:30.941 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:50:30.941 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:50:30.941 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:6K4d9KwaomGPajMvzXX7Jh
15:50:32.158 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:6K4d9KwaomGPajMvzXX7Jh
15:50:41.010 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:50:41.537 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:50:41.538 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:50:41.538 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:32yIEFS62uS5ryhr2Xlooj
15:50:41.683 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:6K4d9KwaomGPajMvzXX7Jh
15:50:42.687 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:32yIEFS62uS5ryhr2Xlooj
15:50:46.349 web-player.aa671a87.js:1 Uncaught (in promise) PlayerAPIClientError: Command didn't receive an acknowledgement within 30000ms
    at web-player.aa671a87.js:1:689034
    at o (vendor~web-player.7d37844a.js:1:163454)
(anonymous) @ web-player.aa671a87.js:1
o @ vendor~web-player.7d37844a.js:1
15:50:46.349 web-player.aa671a87.js:1 Uncaught (in promise) PlayerAPIClientError: Command didn't receive an acknowledgement within 30000ms
    at web-player.aa671a87.js:1:689034
    at o (vendor~web-player.7d37844a.js:1:163454)
(anonymous) @ web-player.aa671a87.js:1
o @ vendor~web-player.7d37844a.js:1
15:50:53.448 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:50:53.924 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:50:53.924 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:50:53.924 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:0CJ1quCQhVX9Ax2jYwwovA
15:50:54.047 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:32yIEFS62uS5ryhr2Xlooj
15:50:55.128 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:0CJ1quCQhVX9Ax2jYwwovA
15:51:00.040 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:0CJ1quCQhVX9Ax2jYwwovA
15:51:00.461 web-player.aa671a87.js:1 Uncaught (in promise) PlayerAPIClientError: Command didn't receive an acknowledgement within 30000ms
    at web-player.aa671a87.js:1:689034
    at o (vendor~web-player.7d37844a.js:1:163454)
(anonymous) @ web-player.aa671a87.js:1
o @ vendor~web-player.7d37844a.js:1
15:51:00.461 web-player.aa671a87.js:1 Uncaught (in promise) PlayerAPIClientError: Command didn't receive an acknowledgement within 30000ms
    at web-player.aa671a87.js:1:689034
    at o (vendor~web-player.7d37844a.js:1:163454)
(anonymous) @ web-player.aa671a87.js:1
o @ vendor~web-player.7d37844a.js:1
15:51:11.044 web-player.aa671a87.js:1 Uncaught (in promise) PlayerAPIClientError: Command didn't receive an acknowledgement within 30000ms
    at web-player.aa671a87.js:1:689034
    at o (vendor~web-player.7d37844a.js:1:163454)
(anonymous) @ web-player.aa671a87.js:1
o @ vendor~web-player.7d37844a.js:1
15:51:11.044 web-player.aa671a87.js:1 Uncaught (in promise) PlayerAPIClientError: Command didn't receive an acknowledgement within 30000ms
    at web-player.aa671a87.js:1:689034
    at o (vendor~web-player.7d37844a.js:1:163454)
(anonymous) @ web-player.aa671a87.js:1
o @ vendor~web-player.7d37844a.js:1
15:51:23.459 web-player.aa671a87.js:1 Uncaught (in promise) PlayerAPIClientError: Command didn't receive an acknowledgement within 30000ms
    at web-player.aa671a87.js:1:689034
    at o (vendor~web-player.7d37844a.js:1:163454)
(anonymous) @ web-player.aa671a87.js:1
o @ vendor~web-player.7d37844a.js:1
Promise.then (async)
trackAcknowledgementRequired @ web-player.aa671a87.js:1
_awaitResponseWithAck @ web-player.aa671a87.js:1
Promise.then (async)
_sendPlayerCommand @ web-player.aa671a87.js:1
play @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
Promise.then (async)
_play @ web-player.aa671a87.js:1
playURI @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
Promise.then (async)
playURI @ web-player.aa671a87.js:1
play @ web-player.aa671a87.js:1
l @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
i.forwardRef.E.leading @ web-player.aa671a87.js:1
e @ vendor~web-player.7d37844a.js:1
S @ vendor~web-player.7d37844a.js:1
onClick @ web-player.aa671a87.js:1
Me @ vendor~web-player.7d37844a.js:1
He @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
Ui @ vendor~web-player.7d37844a.js:1
Vi @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
cl @ vendor~web-player.7d37844a.js:1
Pe @ vendor~web-player.7d37844a.js:1
Gi @ vendor~web-player.7d37844a.js:1
Yt @ vendor~web-player.7d37844a.js:1
zt @ vendor~web-player.7d37844a.js:1
o @ vendor~web-player.7d37844a.js:1
15:51:23.459 web-player.aa671a87.js:1 Uncaught (in promise) PlayerAPIClientError: Command didn't receive an acknowledgement within 30000ms
    at web-player.aa671a87.js:1:689034
    at o (vendor~web-player.7d37844a.js:1:163454)
(anonymous) @ web-player.aa671a87.js:1
o @ vendor~web-player.7d37844a.js:1
setTimeout (async)
(anonymous) @ vendor~web-player.7d37844a.js:1
trackAcknowledgementRequired @ web-player.aa671a87.js:1
_awaitResponseWithAck @ web-player.aa671a87.js:1
Promise.then (async)
_sendPlayerCommand @ web-player.aa671a87.js:1
play @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
Promise.then (async)
_play @ web-player.aa671a87.js:1
playURI @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
Promise.then (async)
playURI @ web-player.aa671a87.js:1
play @ web-player.aa671a87.js:1
l @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
i.forwardRef.E.leading @ web-player.aa671a87.js:1
e @ vendor~web-player.7d37844a.js:1
S @ vendor~web-player.7d37844a.js:1
onClick @ web-player.aa671a87.js:1
Me @ vendor~web-player.7d37844a.js:1
He @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
Ui @ vendor~web-player.7d37844a.js:1
Vi @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
cl @ vendor~web-player.7d37844a.js:1
Pe @ vendor~web-player.7d37844a.js:1
Gi @ vendor~web-player.7d37844a.js:1
Yt @ vendor~web-player.7d37844a.js:1
zt @ vendor~web-player.7d37844a.js:1
o @ vendor~web-player.7d37844a.js:1
15:53:17.629 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:53:18.478 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:0CJ1quCQhVX9Ax2jYwwovA
15:53:18.478 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:53:18.478 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:53:18.478 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:3i3P1mGpV9eRlfKccjDjwi
15:53:20.077 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:3i3P1mGpV9eRlfKccjDjwi
15:53:20.077 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:3i3P1mGpV9eRlfKccjDjwi
15:53:30.405 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:3i3P1mGpV9eRlfKccjDjwi
15:53:47.656 web-player.aa671a87.js:1 Uncaught (in promise) PlayerAPIClientError: Command didn't receive an acknowledgement within 30000ms
    at web-player.aa671a87.js:1:689034
    at o (vendor~web-player.7d37844a.js:1:163454)
(anonymous) @ web-player.aa671a87.js:1
o @ vendor~web-player.7d37844a.js:1
15:53:47.656 web-player.aa671a87.js:1 Uncaught (in promise) PlayerAPIClientError: Command didn't receive an acknowledgement within 30000ms
    at web-player.aa671a87.js:1:689034
    at o (vendor~web-player.7d37844a.js:1:163454)
(anonymous) @ web-player.aa671a87.js:1
o @ vendor~web-player.7d37844a.js:1
15:54:31.523 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:3i3P1mGpV9eRlfKccjDjwi
15:54:32.810 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:3i3P1mGpV9eRlfKccjDjwi
15:54:34.078 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:54:34.636 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Encountered ad in spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:54:34.636 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:ad:7MPxJ4t7LNXoLYaAktMnEE
15:54:34.636 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:2L5FEDC0MU2a6OEkLjByEd
15:54:34.637 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:3i3P1mGpV9eRlfKccjDjwi
15:54:36.086 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:2L5FEDC0MU2a6OEkLjByEd
15:54:36.104 vendor~web-player.7d37844a.js:1 SpotifyAdRemover: Removed ad at spotify:track:2L5FEDC0MU2a6OEkLjByEd
15:55:04.104 web-player.aa671a87.js:1 Uncaught (in promise) PlayerAPIClientError: Command didn't receive an acknowledgement within 30000ms
    at web-player.aa671a87.js:1:689034
    at o (vendor~web-player.7d37844a.js:1:163454)
(anonymous) @ web-player.aa671a87.js:1
o @ vendor~web-player.7d37844a.js:1
Promise.then (async)
trackAcknowledgementRequired @ web-player.aa671a87.js:1
_awaitResponseWithAck @ web-player.aa671a87.js:1
Promise.then (async)
_sendPlayerCommand @ web-player.aa671a87.js:1
play @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
Promise.then (async)
_play @ web-player.aa671a87.js:1
playURI @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
Promise.then (async)
playURI @ web-player.aa671a87.js:1
play @ web-player.aa671a87.js:1
l @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
i.forwardRef.E.leading @ web-player.aa671a87.js:1
e @ vendor~web-player.7d37844a.js:1
S @ vendor~web-player.7d37844a.js:1
onClick @ web-player.aa671a87.js:1
Me @ vendor~web-player.7d37844a.js:1
He @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
Ui @ vendor~web-player.7d37844a.js:1
Vi @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
cl @ vendor~web-player.7d37844a.js:1
Pe @ vendor~web-player.7d37844a.js:1
Gi @ vendor~web-player.7d37844a.js:1
Yt @ vendor~web-player.7d37844a.js:1
zt @ vendor~web-player.7d37844a.js:1
o @ vendor~web-player.7d37844a.js:1
15:55:04.104 web-player.aa671a87.js:1 Uncaught (in promise) PlayerAPIClientError: Command didn't receive an acknowledgement within 30000ms
    at web-player.aa671a87.js:1:689034
    at o (vendor~web-player.7d37844a.js:1:163454)
(anonymous) @ web-player.aa671a87.js:1
o @ vendor~web-player.7d37844a.js:1
setTimeout (async)
(anonymous) @ vendor~web-player.7d37844a.js:1
trackAcknowledgementRequired @ web-player.aa671a87.js:1
_awaitResponseWithAck @ web-player.aa671a87.js:1
Promise.then (async)
_sendPlayerCommand @ web-player.aa671a87.js:1
play @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
Promise.then (async)
_play @ web-player.aa671a87.js:1
playURI @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
Promise.then (async)
playURI @ web-player.aa671a87.js:1
play @ web-player.aa671a87.js:1
l @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
i.forwardRef.E.leading @ web-player.aa671a87.js:1
e @ vendor~web-player.7d37844a.js:1
S @ vendor~web-player.7d37844a.js:1
onClick @ web-player.aa671a87.js:1
Me @ vendor~web-player.7d37844a.js:1
He @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
Ui @ vendor~web-player.7d37844a.js:1
Vi @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
cl @ vendor~web-player.7d37844a.js:1
Pe @ vendor~web-player.7d37844a.js:1
Gi @ vendor~web-player.7d37844a.js:1
Yt @ vendor~web-player.7d37844a.js:1
zt @ vendor~web-player.7d37844a.js:1
o @ vendor~web-player.7d37844a.js:1
15:55:12.097 vendor~web-player.7d37844a.js:1 
        
        
       POST https://gew1-spclient.spotify.com/gabo-receiver-service/v3/events 401 (Unauthorized)
(anonymous) @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
ge @ vendor~web-player.7d37844a.js:1
ve @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
Promise.then (async)
(anonymous) @ vendor~web-player.7d37844a.js:1
_tick @ vendor~web-player.7d37844a.js:1
start @ vendor~web-player.7d37844a.js:1
_sendRetriedRequest @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
Promise.then (async)
_sendRequest @ vendor~web-player.7d37844a.js:1
request @ vendor~web-player.7d37844a.js:1
_uploadBatch @ vendor~web-player.7d37844a.js:1
upload @ vendor~web-player.7d37844a.js:1
upload @ vendor~web-player.7d37844a.js:1
f.n.init.curve @ vendor~web-player.7d37844a.js:1
_tick @ vendor~web-player.7d37844a.js:1
start @ vendor~web-player.7d37844a.js:1
init @ vendor~web-player.7d37844a.js:1
initFlush @ vendor~web-player.7d37844a.js:1
sendToGabito @ vendor~web-player.7d37844a.js:1
flush @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
send @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
s @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
flush @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
o @ vendor~web-player.7d37844a.js:1
setTimeout (async)
(anonymous) @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
sendMetric @ vendor~web-player.7d37844a.js:1
l @ web-player.aa671a87.js:1
l @ web-player.aa671a87.js:1
e.onAfterSend @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
Promise.then (async)
send @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
(anonymous) @ web-player.aa671a87.js:1
create @ web-player.aa671a87.js:1
create @ web-player.aa671a87.js:1
query @ web-player.aa671a87.js:1
getMetadata @ web-player.aa671a87.js:1
queryFn @ web-player.aa671a87.js:1
fetchFn @ vendor~web-player.7d37844a.js:1
y @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
Promise.then (async)
(anonymous) @ vendor~web-player.7d37844a.js:1
Promise.catch (async)
y @ vendor~web-player.7d37844a.js:1
(anonymous) @ vendor~web-player.7d37844a.js:1
```

**Comment by maRci002** [comment]
> Unfortunately this log does not contain a lot of information that helps me to understand the problem. Do you think it happens when the `Command didn't receive an acknowledgement within 30000ms` appears?

Unfortunately no. I will send new logs when it happens.

**Comment by maRci002** [comment]
WIll issue a new issue if happens
